### PR TITLE
Adds circular reference test, dependency test and prefilters packages before sorting.

### PR DESCRIPTION
**Pull request by stesi561**
to address https://github.com/civicrm/composer-compile-plugin/issues/13

This checks what happens if adding a package A that requires package B that requires package A.

### CODE REVIEW

**Comment by homotechsual** [comment]
+1 from me on this. It works, it's performant (relatively speaking) and test suites like it!

**Comment by totten** [comment]
@stesi561 Test is nice, and in principle I like the idea of using `Composer\Util\PackageSorter`. FWIW, that class doesn't appear until composer v1.9. (As a matter of happenstance... most of c.o tests are currently running composer 1.7, and I think I'd done first round of dev with composer 1.6.) For sure, these are a bit dated. It's really just that we need a some kind of control on the version of `composer` itself.

As I see it:

* The ideal would be a version-constraint in `composer-compile-plugin:composer.json` -- if you try to install `composer-compile-plugin` on an older version of composer, then it would be rejected. Unfortunately, the official rule is that plugins should depend on `composer-plugin-api` - but that number was held at `1.1.0` for a long time (nearly every version of composer `1.x` has API  `1.1.0`). AFAICS, there's no way to express the appropriate constraint.
* As a fallback, perhaps we would have civicrm-buildkit pin to a specific version of composer. That at least ensures internal systems are under control. But it doesn't help all the random environments out there that are unattuned to composer version.
* The slightly messier - but more effective - way to cope might be a runtime-check for `Composer\Util\PackageSorter`:
    * If `Composer\Util\PackageSorter` is available, use it.
    * If it's not, use an included `PackageSorter` and emit a warning. (*This system appears to be using an older version of "composer" and may have difficulty with some ordering tasks. Please update to composer 1.10+ or 2.0+.*)

**Comment by stesi561** [comment]
As per discussion on chat - This was giving a compilation error - due to the compile tasks not being generated in the right order.

However I'm now no longer able to replicate this. 

I'm wondering if we need some additional tests added that tests ordering? I don't have my head around the required ordering enough yet though. 

From https://blog.packagist.com/composer-2-0-is-now-available/
"
As for Composer 1.x, it is now more or less EOL. It will also receive critical fixes if anything comes up but the goal for everyone should be to migrate to 2.x as soon as possible.
"

However I feel like we are not quite ready for composer 2.x in civicrm?
Given this I think fine to assume that people will need to get to >= 1.10 for this to work. 
I'll redo this to detect the existence of Composer\Util\PackageSorter and use it otherwise fall back to the previous code with a warning.

**Comment by totten** [comment]
> As per discussion on chat - This was giving a compilation error - due to the compile tasks not being generated in the right order.
>
> However I'm now no longer able to replicate this.

FWIW, it still fails for me. One possibility - if you're periodically re-running the test on the same folder, then there might be contamination between trial runs -- e.g. trial `#7` manages to generate `CCL.php`, then the file exists for trial `#8`, trial `#9`, etc. The failure would seem to disappear because (once the file is created) it ceases to matter if the order is correct. But it still matters for a clean build.

When doing a manual run, I try to control for this possibility by always running

```
rm composer.lock vendor/ -rf ; composer install
```

Anywho, I pulled up the branch and did some similar jiggerydo (like we discussed on Mattermost) to make a test build of `civicrm/civicrm-core` and then [print the sorted package list](https://gist.github.com/totten/3dafb259e753c225359371c6bcbae88e). Here's a snippet of output from `Composer\Util\PackageSorter`:

```
    0 => 'adrienrn/php-mimetyper',
    1 => 'brick/math',
    2 => 'brick/money',
    3 => 'cache/integration-tests',
    4 => 'cache/tag-interop',
    5 => 'civicrm/civicrm-core',
    6 => 'civicrm/civicrm-cxn-rpc',
    7 => 'civicrm/composer-compile-lib',
    8 => 'civicrm/composer-compile-plugin',
    9 => 'civicrm/composer-downloads-plugin',
    10 => 'cweagans/composer-patches',
    11 => 'dflydev/apache-mime-types',
    12 => 'dompdf/dompdf',
    13 => 'electrolinux/phpquery',
    14 => 'guzzlehttp/guzzle',
```

I theorized that maybe the problem is one of orientation. `Civi\CompilePlugin\PackageSorter` (abbrev "CompileSorter") specifies *ascending* order (from least-dependent to most-dependent). Perhaps `Composer\Util\PackageSorter` (abbrev "ComposerSorter") just uses *descending* order (from most-dependent to least-dependent)?

But honestly the output from ComposerSorter doesn't make sense for either orientation.

* Recall that `civicrm-core` (5) depends on both `php-mimetyper` (0) and `composer-compile-lib` (7).
* If ComposerSorter is intended to return in ascending order, then:
    * It correctly places `php-mimetyper` (0) before `civicrm-core` (5).
    * It incorrectly places `civicrm-core`  (5) before `composer-compile-lib` (7).
* If ComposerSorter is intended to return in descending order, then:
    * It correctly places `civicrm-core` (5) before `composer-compile-lib` (7).
    * It incorrectly places `php-mimetyper` (0) before `civicrm-core` (5)

So... this order doesn't make any sense.

**Comment by stesi561** [comment]
Agree. Perhaps I was overly optimistic in thinking that this very similarly named class would provide the required output!

From: https://github.com/composer/composer/commit/7c891701e6ca13a79e0131f06c9eddfd9a315c9b
"PackageSorter weighs the importance of a packageby counting how many times it is required by other packages. This works by calculating the weight for each package name."

Which makes much more sense given the code seemed much simpler than what the existing code was!

However I feel like perhaps our use case is not so much how many times something is required, but ordering such that for each item l[x] in the list (l)  there is no item l[y] such that y < x and l[x] depends on l[y]. In which case we are perhaps back to identifying there is a circular dependency and picking some way to get out of it?

**Comment by stesi561** [comment]
I feel like the solution to picking where to break the circular dependency either comes down to

1. breaking it above items listed in composer.json - with the assumption that if you are putting something in composer.json, then this shouldn't have anything else depend on it that is also included in the project - as you could therefore avoid including it. Perhaps emit some sort of warning to this effect if a circular dependency is detected and it breaks it based on this logic.

2. hard coding in some decisions assuming that not many projects have circular dependencies (is this the case?) and therefore why spend a lot of time accounting for it in a complete way. Submit issues on these projects for them to resolve this with the goal of removing the hard coding in the future.

3. Instead of looking at the composer dependency tree we actually need to do the dependency resolving of the tasks themselves if this is even possible?

**Comment by totten** [comment]
> I feel like the solution to picking where to break the circular dependency either comes down to
>
> 1. breaking it above items listed in composer.json - with the assumption that if you are putting something in composer.json, then this shouldn't have anything else depend on it that is also included in the project - as you could therefore avoid including it

The idea of figuring how to ignore some packages sounds promising. I'm not entirely sure I follow the sentence correctly, but let me repeat-back something similar and see if it makes sense:

There's an `InstallGraph` (dependencies among packages installed in the local root-project, incl all transitive dependencies), and `CompileSorter` is currently trying to sort the full `InstallGraph`. In reality, we only care about the `CompileGraph` (dependencies among packages with compilation-tasks). If we focus our effort on the `CompileGraph`, then we can ignore any incidental messiness in the bigger `InstallGraph`.

The `CompileGraph` is a reduction of the `InstallGraph`. The next step here is to write an algorithm that derives `CompileGraph` from `InstallGraph` (e.g. repeatedly pruning non-compilation leaf-nodes).

> 2. hard coding in some decisions assuming that not many projects have circular dependencies (is this the case?) and therefore why spend a lot of time accounting for it in a complete way. Submit issues on these projects for them to resolve this with the goal of removing the hard coding in the future.

Right. The main trade-off being the potential for whack-a-mole.

On the plus side... if we had a way of hard-coding some decisions re:phpunit and symfony components, then it might become easier to address a current gap. (Currently, it doesn't try to sort `dev-requires` or `suggests` because I saw too many cycles hitting dev-tools like phpunit.)

Then again, we could probably get the same benefit by (1), eg focusing more precisely on `CompileGraph`.

> 3. Instead of looking at the composer dependency tree we actually need to do the dependency resolving of the tasks themselves if this is even possible?

Oh... so a dependency between tasks would say something like this "packageB:task2 depends on packageA:task1"? The only way I can think to get that would be to require explicit metadata, which would be fairly onerous to maintain. I can't think of anything pleasant/clever.

> (@MikeyMJCO)  It works, it's performant (relatively speaking) and test suites like it

Just to clarify performance bit... this was saying something like... "since upstream already uses ComposerSorter, it must be fast enough relative to industry expectations"? Alternatively, this could be saying "in scenario XYZ, ComposerSorter is visibly faster than CompileSorter"? (Which would be good to know. But my assumption is that the package list is small enough that sorting is de-facto instantaneous. As a quick sanity-check... I took `civicrm-core`'s dependency graph and checked the sort time with both sorters. The difference is 0.0001 seconds vs 0.0002 seconds. I'm going to continue assuming that's fast enough until someone finds contrary data. :) )

**Comment by stesi561** [comment]
Okay I like the concept of building the CompileGraph however this looks like it complicates things a bit. 
My read of the code is that TaskList already has the logic (in loadPackage) to detect if a package has compilation tasks.

Currently we have roughly:

Get the Packages
Sort the Packages
Check for Compilation Tasks and Trigger and Event if found. 

If we were going to go this way I think we need to either reorder this process - or remove the logic of identifying compilation tasks into a function separate from triggering the event - as I'm assuming order matters when it comes to when the events get triggered.

I think probably better to switch the order around - that reduces scanning of composer.json files, however this would be a larger change to the code than just pulling out the bit that does the detection so we would:

Get the Packages
Scan each package for compile tasks and record this in a way that's accessible in the Package Sorter I assume easiest (but doesn't feel very correct?) to  dynamically add a property to the Package.

I'm not sure if it might not be easier to actually create some sort of graph structure to do this processing on.

**Comment by stesi561** [comment]
@totten I've updated to prefilter the packages before sorting - this means we now only have an issue if packages with compilation tasks have a circular dependency. I wasn't clear about the approach you had used - why prefer composer.json source to load extra over getExtra? etc so have just replicated as much as possible. This is now failing the EventTest::testComposerInstall and eventTest::testDryRun however is this due to these expecting Pre and post compile tasks to run on packages that don't have compile tasks? Or is my filtering not working correctly?

**Comment by homotechsual** [comment]
@totten any insight on the test failures?

**Comment by stesi561** [comment]
It seems the test was updated here -> https://github.com/civicrm/composer-compile-plugin/commit/8b37f3e06c342596e6e0a7e62645820c9f9cc183

**Comment by totten** [comment]
> I've updated to prefilter the packages before sorting - this means we now only have an issue if packages with compilation tasks have a circular dependency

Excellent!

> why prefer composer.json source to load extra over getExtra?

IIRC, it was about using the most up-to-date configuration. If you're working on a patch to a package within the local source-tree, you might edit the local `composer.json` to try changing/adding/removing a compilation task. I believe that `getExtra()` returns the metadata based on how the package was last published -- whereas reading the `composer.json` file gives you the metadata as it currently exists on the local system. ([comment](https://github.com/civicrm/composer-compile-plugin/blob/35bd4fa/src/TaskList.php#L68-L69))

> (@stesi561) This is now failing the EventTest::testComposerInstall and eventTest::testDryRun however is this due to these expecting Pre and post compile tasks to run on packages that don't have compile tasks? Or is my filtering not working correctly?
>
> (@MikeyMJCO) any insight on the test failures?

Yes, I agree with the first theory - it's failing because `EventTest` involves 3 packages, and it is expecting {PRE,POST}_COMPILE_LIST to fire on all 3 packages. With the filtering in place, it only fires on one package (i.e. the package with an explicit task list).

I guess the question is whether this is acceptable. Currently, there is only one listener for these events, and its job is to rewrite some of the task fields for backward-compatibility (ie `OldTaskAdapter`). For that use-case, it's fine to only fire if there are extant tasks.

In principle, you could have a plugin which registers tasks in some other way. (Ex: "Write a plugin `composer-auto-min` which automatically writes minified versions of any files like `css/*.css`." This could be written using `PRE_COMPILE_LIST` and extra minification tasks.)  For this case, skipping the event would be problematic. Of course, AFAIK, this case is counterfactual.

So *ideally* we would allow this and we would fire `PRE_COMPILE_LIST` even if the package's `composer.json` doesn't explicitly list any tasks. (We would need to fire the event before/while determining if `packageHasCompileTasks`.) OTOH, this is v0.x - so we could just live with the limitation. If the patch seems beyond reach right now, then we could add a note to `doc/develop.md` ("Events") to say (a) that this event has a limitation and (b) that it may change in a future release.

(EDIT) So if we were just going to live with the limit for the moment, then you could `doc/develop.md`, then edit `EventTest::startupLines()` and reduce the number of expected packages from 3 to 1

**Comment by stesi561** [comment]
> So ideally we would allow this and we would fire PRE_COMPILE_LIST even if the package's composer.json doesn't explicitly list any tasks. (We would need to fire the event before/while determining if packageHasCompileTasks.) OTOH, this is v0.x - so we could just live with the limitation. If the patch seems beyond reach right now, then we could add a note to doc/develop.md ("Events") to say (a) that this event has a limitation and (b) that it may change in a future release.

In principle it shouldn't be difficult to do this however, I'm pretty sure that these events were previously ordered. And as we are now not sorting packages that don't have compile tasks (we are only building the graph of packages with tasks) we'd then need to either fire these events with no ordering for all tasks - or build the graph of packages with tasks, build another list of ones without tasks and fire in order for those with tasks and with no defined order for those without tasks. 

Otherwise we are back to the start and needing to detect and resolve cycles in dependencies?

I don't fully understand what is going on here but I feel like not firing an event for packages that don't have defined tasks is the easiest way forward currently!

**Comment by totten** [comment]
> In principle it shouldn't be difficult to do this however, I'm pretty sure that these events were previously ordered... we'd then need to either fire these events with no ordering for all tasks - or build the graph of packages with tasks

Yeah, I see what you're saying.

IMHO it's acceptable to fire `*-compile-list` without a guarantee of package-order (although maybe it's preferable to ensure reproducibility with some trivial ordering - eg alphabetical):

* For the examples earlier ([OldTaskAdapter and hypothetical composer-auto-min](https://github.com/civicrm/composer-compile-plugin/pull/14#issuecomment-758410784)), it wouldn't matter.
* I have a feeling that there's a deeper reason, but I'm not sure what it is. Something like this....
    * The most substantive preconditions when using `*-compile-list` are that (a) all packages have been downloaded and (b) no packages have been compiled. The order in which you augment the TaskLists doesn't affect those preconditions.
    * For package-order to influence `*-compile-list` listeners, you would need a use-case where PkgA.TaskList changes depending on PkgB.TaskList. That's a niche within a niche (for which I'm struggling to see a good use-case).
     * The `*-compile-list` listeners operate at a more generic level where they can only rely on composer-internal services (ie they don't rely on downstream services of PkgA/PkgB).

> I don't fully understand what is going on here but I feel like not firing an event for packages that don't have defined tasks is the easiest way forward currently!

Yeah, it's not important for current/live use-cases -- the easy path is to just cleanup the docs and other test. Just cherry-pick these two bits:

https://github.com/totten/composer-compile-plugin/commits/fuzionnz-master

**Comment by totten** [comment]
@stesi561 Thanks for working through this. 

Merged and tagged as v0.15.

**Pull request merged**
