### PR TITLE
Don't crash on windows

### PR DESCRIPTION
**Pull request by demeritcowboy**
Windows doesn't like the multiline command.

### CODE REVIEW

**Comment by seamuslee001** [comment]
I tested this and it works for me @totten

**Comment by totten** [comment]
@demeritcowboy @seamuslee001 Ah, interesting problem.

So at first glance, I thought this was OK - but then it struck me: "What data in that command involves newline characters?" Most of the args shouldn't. It's probably the `$event->getTask()->definition`, because that's an open-ended thing. I guess that raised problems on account of `var_export()`s formatting. But the `$definition` is user-supplied data, and there could be other wonky stuff in there.

Are you guys down with 90990bf - i.e. passing the `definition` through a base64 filter? On an example build (per `ScssPhpMethodTest.php`) on Linux, it runs the subcommand as follows:

```
> shell-runner: @php -r 'require_once '\''/home/totten/src/sandbox/vendor/autoload.php'\'';
 \ScssExample\ScssExample::make(json_decode(base64_decode('\''eyJhY3Rpdm
UiOnRydWUsInRpdGxlIjoiPGNvbW1lbnQ+dGVzdFwvZ25vY2NoaTxcL2NvbW1lbnQ+Ojxjb2
1tZW50PjE8XC9jb21tZW50PiIsIndhdGNoLWZpbGVzIjpudWxsLCJwaHAtbWV0aG9kIjoiXF
xTY3NzRXhhbXBsZVxcU2Nzc0V4YW1wbGU6Om1ha2UiLCJzb3VyY2UtZmlsZSI6IlwvaG9tZV
wvdG90dGVuXC9zcmNcL3NhbmRib3hcL3ZlbmRvclwvdGVzdFwvZ25vY2NoaVwvY29tcG9zZX
IuanNvbiJ9'\''), 1));'
```

(Note: the command actually appears as one-line, but I've edited for readability on github ui).

**Comment by demeritcowboy** [comment]
It's clever - give me a few minutes to try it out.

**Comment by demeritcowboy** [comment]
Runs good. There's just some whitespace that snuck into line 49.

**Comment by totten** [comment]
Good catch @demeritcowboy. (Apparently my PSR-12 style-checker doesn't complain about that...)

Whitespace fixed. Tests pass again. Merging.

**Comment by totten** [comment]
Tagged as v0.7.

**Comment by demeritcowboy** [comment]
Thanks guys!

**Pull request merged**
