### PR TITLE
Fix for Composer 2 / PHP with thread safe disabled, putenv() doesn't work

### PR DESCRIPTION
**Pull request by jackrabbithanna**
quick fix for issue 17: https://github.com/civicrm/composer-compile-plugin/issues/17

Probably not the end all of fixes wrt this, but makes it work.

### CODE REVIEW

**Comment by demeritcowboy** [comment]
It looks like composer v1 doesn't have that utility function. Interestingly the other passing test job 99.1 says it's configured for composer v1 but ends up using v2.

One option would be to check method_exists() first. Or provide a polyfill function for v1.

**Comment by demeritcowboy** [comment]
I found the machine where this had come up for me and tried the patch with composer 2 and it worked and generated the css file.

**Comment by totten** [comment]
> It looks like composer v1 doesn't have that utility function. Interestingly the other passing test job 99.1 says it's configured for composer v1 but ends up using v2.

Hrm, that output is hard to read clearly. I *think* it's saying that the baseline environment in Travis is setting up composer v2, and then it invokes [./scripts/travis-ci.sh before_script](https://github.com/civicrm/composer-compile-plugin/blob/ad3dda7/scripts/travis-ci.sh#L54) which downloads composer v1. You can drilldown in the output to see it downloads:

Screen Shot 2021-09-29 at 3 57 16 PM

But if the availability of `Platform::putEnv()` really is based on version, then `99.1` should've failed the same way as `99.4`. 😕  Maybe something changed in the Linux base image for how `composer` gets into `PATH` (interfering with the v1 copy)? Or maybe there's some other issue besides composer-version at play?

In either case, for purposes of this PR, we have some jobs hitting each version (eg 99.4+100.4/composer-v1 vs 99.3+100.3/composer-v2), and all jobs are passing  with the latest revision. So the patch is good.

Review recap: Change looks pretty reasonable; it works for both Mark+Dave; and CI is happy with the `method_exists()` bit.  Merging.

**Comment by totten** [comment]
Tagged as v0.17.

**Comment by demeritcowboy** [comment]
Ah yes I missed the little gray triangles. 👍 
So yeah a little confusing. There is a test that has "S"kipped in the ".1" run but all of them run in ".4". Maybe that's the diff.

**Pull request merged**
